# coding: utf-8

"""
    SEARCH Gateway Service

    SEARCH Gateway Service using Flask, OpenAPI and Connexion  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class CheckGraphDto(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'is_acyclic': 'bool'
    }

    attribute_map = {
        'is_acyclic': 'isAcyclic'
    }

    def __init__(self, is_acyclic=None):  # noqa: E501
        """CheckGraphDto - a model defined in Swagger"""  # noqa: E501
        self._is_acyclic = None
        self.discriminator = None
        self.is_acyclic = is_acyclic

    @property
    def is_acyclic(self):
        """Gets the is_acyclic of this CheckGraphDto.  # noqa: E501


        :return: The is_acyclic of this CheckGraphDto.  # noqa: E501
        :rtype: bool
        """
        return self._is_acyclic

    @is_acyclic.setter
    def is_acyclic(self, is_acyclic):
        """Sets the is_acyclic of this CheckGraphDto.


        :param is_acyclic: The is_acyclic of this CheckGraphDto.  # noqa: E501
        :type: bool
        """
        if is_acyclic is None:
            raise ValueError("Invalid value for `is_acyclic`, must not be `None`")  # noqa: E501

        self._is_acyclic = is_acyclic

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(CheckGraphDto, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CheckGraphDto):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
