# coding: utf-8

# flake8: noqa
"""
    L3S Gateway for SEARCH

    Welcome to the Swagger UI documentation site!  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

# import models into model package
from l3s_swagger_client.models.recsys_srv_request import RecsysSrvRequest
from l3s_swagger_client.models.retrieve import Retrieve
from l3s_swagger_client.models.search_srv_request import SearchSrvRequest
from l3s_swagger_client.models.service import Service
from l3s_swagger_client.models.testing import Testing
from l3s_swagger_client.models.todo import Todo
