# coding: utf-8

"""
    Skill Repository

    The API description of the Skill Repository.  # noqa: E501

    OpenAPI spec version: 0.4.13
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import re  # noqa: F401

# python 2 and python 3 compatibility library
import six

from swagger_client.api_client import ApiClient


class LearningPathApi(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    Ref: https://github.com/swagger-api/swagger-codegen
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient()
        self.api_client = api_client

    def learning_path_mgmt_controller_add_learningpath(self, body, **kwargs):  # noqa: E501
        """learning_path_mgmt_controller_add_learningpath  # noqa: E501

        Creates a new learningpath at the specified repository and returns the created learningpath.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.learning_path_mgmt_controller_add_learningpath(body, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param LearningPathCreationDto body: (required)
        :return: LearningPathDto
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.learning_path_mgmt_controller_add_learningpath_with_http_info(body, **kwargs)  # noqa: E501
        else:
            (data) = self.learning_path_mgmt_controller_add_learningpath_with_http_info(body, **kwargs)  # noqa: E501
            return data

    def learning_path_mgmt_controller_add_learningpath_with_http_info(self, body, **kwargs):  # noqa: E501
        """learning_path_mgmt_controller_add_learningpath  # noqa: E501

        Creates a new learningpath at the specified repository and returns the created learningpath.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.learning_path_mgmt_controller_add_learningpath_with_http_info(body, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param LearningPathCreationDto body: (required)
        :return: LearningPathDto
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['body']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method learning_path_mgmt_controller_add_learningpath" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'body' is set
        if ('body' not in params or
                params['body'] is None):
            raise ValueError("Missing the required parameter `body` when calling `learning_path_mgmt_controller_add_learningpath`")  # noqa: E501

        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'body' in params:
            body_params = params['body']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/learningpaths/add_learningpath', 'POST',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='LearningPathDto',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def learning_path_mgmt_controller_get_learning_path(self, learningpath_id, **kwargs):  # noqa: E501
        """learning_path_mgmt_controller_get_learning_path  # noqa: E501

        Returns the specified learningpath.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.learning_path_mgmt_controller_get_learning_path(learningpath_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str learningpath_id: (required)
        :return: LearningPathDto
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.learning_path_mgmt_controller_get_learning_path_with_http_info(learningpath_id, **kwargs)  # noqa: E501
        else:
            (data) = self.learning_path_mgmt_controller_get_learning_path_with_http_info(learningpath_id, **kwargs)  # noqa: E501
            return data

    def learning_path_mgmt_controller_get_learning_path_with_http_info(self, learningpath_id, **kwargs):  # noqa: E501
        """learning_path_mgmt_controller_get_learning_path  # noqa: E501

        Returns the specified learningpath.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.learning_path_mgmt_controller_get_learning_path_with_http_info(learningpath_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str learningpath_id: (required)
        :return: LearningPathDto
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['learningpath_id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method learning_path_mgmt_controller_get_learning_path" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'learningpath_id' is set
        if ('learningpath_id' not in params or
                params['learningpath_id'] is None):
            raise ValueError("Missing the required parameter `learningpath_id` when calling `learning_path_mgmt_controller_get_learning_path`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'learningpath_id' in params:
            path_params['learningpathId'] = params['learningpath_id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/learningpaths/{learningpathId}', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='LearningPathDto',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def learning_path_mgmt_controller_list_learning_paths(self, **kwargs):  # noqa: E501
        """learning_path_mgmt_controller_list_learning_paths  # noqa: E501

        Lists all learning paths.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.learning_path_mgmt_controller_list_learning_paths(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :return: LearningPathListDto
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.learning_path_mgmt_controller_list_learning_paths_with_http_info(**kwargs)  # noqa: E501
        else:
            (data) = self.learning_path_mgmt_controller_list_learning_paths_with_http_info(**kwargs)  # noqa: E501
            return data

    def learning_path_mgmt_controller_list_learning_paths_with_http_info(self, **kwargs):  # noqa: E501
        """learning_path_mgmt_controller_list_learning_paths  # noqa: E501

        Lists all learning paths.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.learning_path_mgmt_controller_list_learning_paths_with_http_info(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :return: LearningPathListDto
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = []  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method learning_path_mgmt_controller_list_learning_paths" % key
                )
            params[key] = val
        del params['kwargs']

        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/learningpaths/showAllLearningPaths', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='LearningPathListDto',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)
