# coding: utf-8

"""
    Skill Repository

    The API description of the Skill Repository.  # noqa: E501

    The version of the OpenAPI document: 0.4.2
    Generated by: https://openapi-generator.tech
"""

from openapi_client.paths.auth_login.post import AuthControllerLogin
from openapi_client.paths.auth_register.post import AuthControllerRegister


class AuthenticationApi(
    AuthControllerLogin,
    AuthControllerRegister,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
