# coding: utf-8

"""
    Skill Repository

    The API description of the Skill Repository.  # noqa: E501

    The version of the OpenAPI document: 0.4.2
    Generated by: https://openapi-generator.tech
"""

from openapi_client.paths.learning_units_add_learning_unit.post import SearchLearningUnitControllerAddLearningUnitSearch
from openapi_client.paths.learning_units_learning_unit_id.get import SearchLearningUnitControllerGetLearningUnit
from openapi_client.paths.learning_units_show_all_learning_units.get import SearchLearningUnitControllerListLearningUnits


class LearningUnitApi(
    SearchLearningUnitControllerAddLearningUnitSearch,
    SearchLearningUnitControllerGetLearningUnit,
    SearchLearningUnitControllerListLearningUnits,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
