# coding: utf-8

"""
    Skill Repository

    The API description of the Skill Repository.  # noqa: E501

    The version of the OpenAPI document: 0.4.2
    Generated by: https://openapi-generator.tech
"""

from openapi_client.paths.learningpaths_add_learningpath.post import LearningPathMgmtControllerAddLearningpath
from openapi_client.paths.learningpaths_learningpath_id.get import LearningPathMgmtControllerGetLearningPath
from openapi_client.paths.learningpaths_show_all_learning_paths.get import LearningPathMgmtControllerListLearningPaths


class LearningPathApi(
    LearningPathMgmtControllerAddLearningpath,
    LearningPathMgmtControllerGetLearningPath,
    LearningPathMgmtControllerListLearningPaths,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
