# coding: utf-8

"""
    Skill Repository

    The API description of the Skill Repository.  # noqa: E501

    The version of the OpenAPI document: 0.4.2
    Generated by: https://openapi-generator.tech
"""

from openapi_client.paths.nuggets_add_nugget.post import NuggetMgmtControllerAddNugget
from openapi_client.paths.nuggets_nugget_id.get import NuggetMgmtControllerGetNugget
from openapi_client.paths.nuggets_show_all_nuggets.get import NuggetMgmtControllerListNuggets


class NuggetApi(
    NuggetMgmtControllerAddNugget,
    NuggetMgmtControllerGetNugget,
    NuggetMgmtControllerListNuggets,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
