# coding: utf-8

"""
    Skill Repository

    The API description of the Skill Repository.  # noqa: E501

    The version of the OpenAPI document: 0.4.2
    Generated by: https://openapi-generator.tech
"""

from openapi_client.paths.skill_repositories_repository_id_skill_add_skill.post import SkillMgmtControllerAddSkill
from openapi_client.paths.skill_repositories_skill_create.post import SkillMgmtControllerCreateRepository
from openapi_client.paths.skill_repositories_skill_skill_id.get import SkillMgmtControllerGetSkill
from openapi_client.paths.skill_repositories_show_own.get import SkillMgmtControllerListRepositories
from openapi_client.paths.skill_repositories_show_all_skills.get import SkillMgmtControllerListSkills
from openapi_client.paths.skill_repositories_repository_id.get import SkillMgmtControllerLoadRepository
from openapi_client.paths.skill_repositories_resolve_repository_id.get import SkillMgmtControllerLoadResolvedRepository
from openapi_client.paths.skill_repositories.post import SkillMgmtControllerSearchForRepositories


class SkillApi(
    SkillMgmtControllerAddSkill,
    SkillMgmtControllerCreateRepository,
    SkillMgmtControllerGetSkill,
    SkillMgmtControllerListRepositories,
    SkillMgmtControllerListSkills,
    SkillMgmtControllerLoadRepository,
    SkillMgmtControllerLoadResolvedRepository,
    SkillMgmtControllerSearchForRepositories,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
