# coding: utf-8

"""
    Skill Repository

    The API description of the Skill Repository.  # noqa: E501

    The version of the OpenAPI document: 0.4.2
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from openapi_client import schemas  # noqa: F401


class SkillRepositoryListDto(
    schemas.DictSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """


    class MetaOapg:
        required = {
            "repositories",
        }
        
        class properties:
            
            
            class repositories(
                schemas.ListSchema
            ):
            
            
                class MetaOapg:
                    
                    @staticmethod
                    def items() -> typing.Type['SkillRepositoryDto']:
                        return SkillRepositoryDto
            
                def __new__(
                    cls,
                    _arg: typing.Union[typing.Tuple['SkillRepositoryDto'], typing.List['SkillRepositoryDto']],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'repositories':
                    return super().__new__(
                        cls,
                        _arg,
                        _configuration=_configuration,
                    )
            
                def __getitem__(self, i: int) -> 'SkillRepositoryDto':
                    return super().__getitem__(i)
            __annotations__ = {
                "repositories": repositories,
            }
    
    repositories: MetaOapg.properties.repositories
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["repositories"]) -> MetaOapg.properties.repositories: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["repositories", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["repositories"]) -> MetaOapg.properties.repositories: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["repositories", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *_args: typing.Union[dict, frozendict.frozendict, ],
        repositories: typing.Union[MetaOapg.properties.repositories, list, tuple, ],
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'SkillRepositoryListDto':
        return super().__new__(
            cls,
            *_args,
            repositories=repositories,
            _configuration=_configuration,
            **kwargs,
        )

from openapi_client.model.skill_repository_dto import SkillRepositoryDto
